proc BuildRCrectSection {id HSec BSec coverH coverB coreID coverID steelID numBarsTop barAreaTop numBarsBot barAreaBot numBarsIntTot barAreaInt nfCoreY nfCoreZ nfCoverZ nfCoverY} {
	################################################
	# BuildRCrectSection $id $HSec $BSec $coverH $coverB $coreID $coverID $steelID $numBarsTop $barAreaTop $numBarsBot $barAreaBot $numBarsIntTot $barAreaInt $nfCoreY $nfCoreZ $nfCoverZ $nfCoverY
	################################################
	# Build fiber rectangular RC section, 1 steel layer top, 1 bot, 1 skin, confined core
	# Define a procedure which generates a rectangular reinforced concrete section
	# with one layer of steel at the top & bottom, skin reinforcement and a 
	# confined core.
	#		by: Silvia Mazzoni, 2006
	#			adapted from Michael H. Scott, 2003
	# 
	# Formal arguments
	#    id - tag for the section that is generated by this procedure
	#    HSec - depth of section, along local-z axis
	#    BSec - width of section, along local-y axis
	#    coverH - clear cover along local-z axis
	#    coverB - clear cover along local-y axis
	#    coreID - material tag for the core patch
	#    coverID - material tag for the cover patches
	#    steelID - material tag for the reinforcing steel
	#    numBarsTop - number of reinforcing bars in the top layer (in the positive z area of the section)
	#    numBarsBot - number of reinforcing bars in the bottom layer (in the negative z area of the section)
	#    numBarsIntTot - TOTAL number of reinforcing bars on the intermediate layers, symmetric about y axis and 2 bars per layer-- needs to be an even integer
	#    barAreaTop - cross-sectional area of each reinforcing bar in top layer
	#    barAreaBot - cross-sectional area of each reinforcing bar in bottom layer
	#    barAreaInt - cross-sectional area of each reinforcing bar in intermediate layer 
	#    nfCoreY - number of fibers in the core patch in the y direction
	#    nfCoreZ - number of fibers in the core patch in the z direction
	#    nfCoverY - number of fibers in the cover patches with long sides in the y direction
	#    nfCoverZ - number of fibers in the cover patches with long sides in the z direction
	#    
	#                        z
	#                        ^
	#                        |     
	#             -----------------------     --
	#             |   o      o      o    |    -- coverH
	#             |                      |     |
	#             |   o             o    |     |
	#    y <----- |          +           |     HSec
	#             |   o             o    |     |
	#             |                      |     |
	#             |   o o o o o o o o    |    -- coverH
	#             -----------------------     --
	#             |----------Bsec--------|
	#             |---| 	coverB 	 |---|
	#
	#                       z
	#                       ^
	#                       |    
	#             ------------------------
	#             |\        cover        /|
	#             | \--------Top--------/ |
	#             |c|                   |c|
	#             |o|                   |o|
	#  y <--------|v|       core      	|v|  HSec
	#             |e|                   |e|
	#             |r|                   |r|
	#             | /--------Bot--------\ |
	#             |/      	cover        \|
	#             -------------------------
	#                       Bsec
	#    
	#
	# Notes
	#    The core concrete ends at the NA of the reinforcement
	#    The center of the section is at (0,0) in the local axis system
	# 
	set HalfB [expr $BSec/2.0];			# The distance from the section z-axis to the edge of the cover concrete -- outer edge of cover concrete
	set HalfH [expr $HSec/2.0];			# The distance from the section y-axis to the edge of the cover concrete -- outer edge of cover concrete
	set CoreHalfB [expr $HalfB-$coverB];		# The distance from the section z-axis to the edge of the core concrete --  edge of the core concrete/inner edge of cover concrete
	set CoreHalfH [expr $HalfH-$coverH];		# The distance from the section y-axis to the edge of the core concrete --  edge of the core concrete/inner edge of cover concrete
	set numBarsInt [expr $numBarsIntTot/2];	# number of intermediate bars per side
	set y1 [expr $CoreHalfB-$barAreaTop/2];	#parameter to define the location of top reinfocement layer
	set z1 [expr $CoreHalfH-$barAreaTop/2];	#parameter to define the location of bottom reinforcement layer
	set nog [expr $numBarsInt+1];			#number of gaps between reinforcement at one side (along z direction)
	set rdist [expr 2*$z1/$nog];			#distance between two consecutive reinforcement at the sides (along z direction)
	
	#Torsional constant calculation for torsional stiffness GJ ( Reference: https://en.wikipedia.org/wiki/Torsion_constant )
    set a [expr max($HalfH, $HalfB)]
    set b [expr min($HalfH, $HalfB)]
    set J [expr $a*pow($b,3)*(16/3-3.36*($b/$a)*(1-pow($b,4)/(12*pow($a,4))))]
	set G 13333.3
		
	# Define the fiber section
	section fiberSec $id -GJ [expr $G*$J] {
		# Define the core patch
		patch quadr $coreID $nfCoreY $nfCoreZ -$CoreHalfB $CoreHalfH -$CoreHalfB -$CoreHalfH $CoreHalfB -$CoreHalfH $CoreHalfB $CoreHalfH
	   
		# Define the four cover patches
		patch quadr $coverID $nfCoverY 2 -$HalfB $HalfH -$CoreHalfB $CoreHalfH $CoreHalfB $CoreHalfH $HalfB $HalfH; 		#cover patch at the top
		patch quadr $coverID $nfCoverY 2 -$CoreHalfB -$CoreHalfH -$HalfB -$HalfH $HalfB -$HalfH $CoreHalfB -$CoreHalfH; 	#cover patch at the bottom
		patch quadr $coverID 2 $nfCoverZ -$HalfB $HalfH -$HalfB -$HalfH -$CoreHalfB -$CoreHalfH -$CoreHalfB $CoreHalfH;		#cover patch at the right-hand side
		patch quadr $coverID 2 $nfCoverZ $CoreHalfB $CoreHalfH $CoreHalfB -$CoreHalfH $HalfB -$HalfH $HalfB $HalfH;			#cover patch at the left-hand side

		# Define reinforcing layers
		layer straight $steelID $numBarsTop $barAreaTop $y1 $z1 [expr -$y1] $z1;					# top layer reinfocement
		layer straight $steelID $numBarsBot $barAreaBot $y1 [expr -$z1]  [expr -$y1] [expr -$z1];		# bottom layer reinforcement
		layer straight $steelID $numBarsInt $barAreaInt  $y1 [expr $z1-$rdist] $y1 [expr -$z1+$rdist];
		layer straight $steelID $numBarsInt $barAreaInt  [expr -$y1] [expr $z1-$rdist] [expr -$y1] [expr -$z1+$rdist];

	};	# end of fibersection definition
};		# end of procedure